import {SUCCESS, FAIL, USER_REGISTER, ADD_TODO, USER_LOGIN} from 'actions/ActionTypes';

export const NOTIFICATION_ERRORS = {
  [USER_REGISTER+FAIL]: USER_REGISTER+FAIL,
  [ADD_TODO+FAIL]: ADD_TODO+FAIL,
  [USER_LOGIN+FAIL]: USER_LOGIN+FAIL
};

export const NOTIFICATION_SUCCESS = {
  [ADD_TODO+SUCCESS]: ADD_TODO+SUCCESS
};